export const ADDTODO = 'ADDTODO'
export const DELETETODO = 'DELETETODO'

export const SETLOCALE = 'SETLOCALE'

export const REQUESTED_DOG = 'REQUSTED_DOG'
export const REQUESTED_DOG_SUCCEEDED = 'REQUESTED_DOG_SUCCEEDED'
export const REQUESTED_DOG_FAILED = 'REQUESTED_DOG_FAILED'
